name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Change to your desired branch, e.g., dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: rajm1995/build-version

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Build Version
        id: build_version
        run: |
          export BUILD_VERSION=$(date +"#%d%m%Y%H%M%S")
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
          echo "Build version: $BUILD_VERSION"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            BUILD_VERSION=${{ env.BUILD_VERSION }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.BUILD_VERSION }}

      - name: Log out from Docker Hub
        run: docker logout
